spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: 1234
    url: jdbc:mysql://localhost:3306/eatfit
    #url: jdbc:mysql://eatfit-db.cxi6gu60cglx.ap-northeast-2.rds.amazonaws.com:3306/eatfit


  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 3dmRfL5IKgJB03yVMt9D
            client-secret: KEzcPmUyUV
            redirect-uri: https://api.eatfit.site/login/oauth2/code/naver
            authorization-grant-type: authorization_code
          kakao:
            client-id: 097610b283cca11c48f0500bddd2ebd8
            client-secret: 5S46LYt51wLzfkeHcZuBE9nszuQDQYM1
            redirect-uri: https://api.eatfit.site/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

client_url: http://localhost:3000/
#client_url: https://eatfit.site/

